### ISSUE TITLE
Invalid token error when starting bot

### ISSUE THREAD

**Issue by philipobrien** [MIPTDeepLearningLab/ConvAI-baseline#2]
<img width="875" alt="screen shot 2017-06-20 at 14 19 09" src="https://user-images.githubusercontent.com/1763813/27335151-79fde514-55c3-11e7-904b-3e88a87caad5.png">

**Comment by madrugado** [comment]
Hi Philip,

It's not a bug, it's a feature: since the token is secret, you should register your own Telegram bot and replace stub token with its token.

You can read how to register your bot here: https://core.telegram.org/bots#botfather

Thank you for your report, I'll add this information to readme.

**Comment by madrugado** [comment]
Added info to README.

**Comment by philipobrien** [comment]
Cool, thanks!
